package pl.com.it_crowd.htmlunit_designer;

import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: bernard
 * Date: 1/12/12
 * Time: 1:02 PM
 * To change this template use File | Settings | File Templates.
 */
public class JavaScriptWatchesForm {
// ------------------------------ FIELDS ------------------------------

    private JPanel rootComponent;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

// -------------------------- OTHER METHODS --------------------------

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return rootComponent;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        rootComponent = new JPanel();
        rootComponent.setLayout(new BorderLayout(0, 0));
        final JLabel label1 = new JLabel();
        label1.setText("JavaScriptWatches");
        rootComponent.add(label1, BorderLayout.CENTER);
    }
}
